name: hicer-nf
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cooler=0.8.7
  - fastqc=0.11.9
  - hdf5=1.10.4
  - hicup=0.7.3
  - java-jdk=8.0.92
  - krbalancing=0.0.5
  - numpy=1.18.1
  - pairix=0.3.7
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.6
  - r=3.6.0
  - samtools=1.10
  - scipy=1.4.1
  - tabix=0.2.6
  - trim-galore=0.6.5
  - pip:
    - multiqc==1.9
